# Generated by Django 4.2.6 on 2023-11-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='package_db',
            new_name='Packagedb',
        ),
    ]
