# Generated by Django 4.2.6 on 2023-11-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_rename_package_db_packagedb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagedb',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='packagedb',
            name='slug',
            field=models.SlugField(blank=True, default=' ', max_length=255),
        ),
        migrations.AddIndex(
            model_name='packagedb',
            index=models.Index(fields=['-time_create'], name='project_man_time_cr_171286_idx'),
        ),
    ]
