# Generated by Django 4.2.6 on 2023-11-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_alter_packagedb_options_packagedb_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedb',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
