# Generated by Django 4.2.6 on 2023-11-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_alter_packagedb_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedb',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
