# Generated by Django 4.2.6 on 2023-11-12 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0006_category_packagedb_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedb',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='project_management.category'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ourpartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='ourpartners/')),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ourpartners', to='project_management.category')),
            ],
        ),
    ]
