# Generated by Django 4.2.6 on 2023-11-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0007_alter_packagedb_cat_ourpartners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourpartners',
            old_name='f_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='ourpartners',
            name='l_name',
        ),
    ]
