# Generated by Django 4.2.6 on 2023-11-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0008_rename_f_name_ourpartners_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ourpartners',
        ),
    ]
