# Generated by Django 4.2.6 on 2023-11-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0009_delete_ourpartners'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterField(
            model_name='packagedb',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Draft'), (True, 'Published')], default=0, verbose_name='Status'),
        ),
    ]
